### PR TITLE
added todo-list project

### PR DESCRIPTION
**Pull request by MananAgr2003**
Kindly Add This Todo-list Project and merge it with appropriate hacktoberfest label

### CODE REVIEW

**Comment by kaal-coder** [comment]
@MananAgr2003 Sure.
 It would be great if you could star the repository.

**Comment by MananAgr2003** [comment]
@kaal-coder Starred. Can I add more projects ?

**Comment by kaal-coder** [comment]
@MananAgr2003 yeah do all in one go and then make a PR.
Make sure your branch is updated.

**Comment by MananAgr2003** [comment]
@kaal-coder kindly merge this PR With The Apt hacktober Label I'll add more projects later kindly merge this PR first

**Comment by kaal-coder** [comment]
@MananAgr2003 Thanks for contributing
But it seems like my repository has been excluded from the hacktoberfest.
The reason seems unknown.
So you can just do one thing, hop on to my other repository and do the same procedure.
I'll accept ASAP I get the request.

https://github.com/kaal-coder/hacktoberfest

**Comment by MananAgr2003** [comment]
kindly check the other repo i have just made a PR

**Pull request merged**
