### PR TITLE
Basics of C

### PR DESCRIPTION
**Pull request by yashpatel08**
C PROGRAMS 

All programs are in c language . if it is helpfull then please tell me so i can upload more programs in this repo.  @kaal-coder
@kaal-coder

### CODE REVIEW

**Comment by kaal-coder** [comment]
@yashpatel08 Make the comment name valid and if possible star the repository.

**Comment by yashpatel08** [comment]
I have star that respo so please see that and tell me asap.



Patel Yash J.
college - Gec bhavnagar
branch - I.T
city - Dhoraji
*"Happiness is not a destination it is a way of life "*

**Comment by kaal-coder** [comment]
@yashpatel08 I have done the required changes added the labels and merged your PR.
You can still add any of your projects on any domain, which will be highly appreciated.

**Comment by yashpatel08** [comment]
Thanks a lot.
Patel Yash J.
college - Gec bhavnagar
branch - I.T
city - Dhoraji
*"Happiness is not a destination it is a way of life "*

**Pull request merged**
