### PR TITLE
Record-Manager Web Application

### PR DESCRIPTION
**Pull request by Git-Akshat01**
Record-Manager Web Application is an application that manages the records. It is made using:- 
Front-end :- Html, CSS.
Back-end:- Java.
Database:- Oracle.

It is for #hacktoberfest by @Git-Akshat01

### CODE REVIEW

**Review by Git-Akshat01 — COMMENTED** [review]
Please merge the project in your repository under the banner of @hacktoberfest

**Comment by kaal-coder** [comment]
@Git-Akshat01 Thanks for contributing
But it seems like my repository has been excluded from the hacktoberfest.
The reason seems unknown.
So you can just do one thing, hop on to my other repository and do the same procedure.
I'll accept ASAP I get the request.

https://github.com/kaal-coder/hacktoberfest

**Comment by Git-Akshat01** [comment]
Hi! Kaushik.
I am doing it right now. Within a couple of minutes, I will send the
request to merge.

**Comment by Git-Akshat01** [comment]
Kaushik I had done the pull request. Please Review.

**Pull request merged**
